# Generated by Django 6.0.2 on 2026-02-10 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='data_alteracao',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_alteracao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
