# Generated by Django 6.0.2 on 2026-02-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_alteracao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
